name: Build & publish nuget
env:
  VERSION: 0.5.0
  
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test

    # Build debug and release versions
    - name: Restore the application
      run: dotnet pack --configuration Release

    # Get authentication
    - name: Authenticate with github packages repository
      run: dotnet nuget add source --username jleugeri --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/jleugeri/index.json"

    # Actually publish the result
    - name: Publish nuget
      run: dotnet nuget push "src/bin/Release/SystemCSharp.$VERSION.nupkg" --source "github"
