name: Build & publish nuget
env:
  VERSION: 0.5.0
  
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test

    # Compile
    - name: Execute unit tests
      run: dotnet build --configuration Release

    # Build debug and release versions
    - name: Restore the application
      run: dotnet pack --configuration Release

    # Get authentication
    - name: Authenticate with github packages repository
      run: 
        dotnet nuget add source --username jleugeri --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github 
        dotnet nuget add source --username NeuroMan --password ${{ secrets.NUGET_ORG_API_KEY }} --store-password-in-clear-text --name nuget

    # Actually publish the result on github packages
    - name: Publish nuget on GitHub
      run: dotnet nuget push "src/bin/Release/SystemCSharp.$VERSION.nupkg" --source "github"
    
    # Publish the result on NuGet.org repository
    - name: Publish nuget on NuGet.org
      run: dotnet nuget push push "src/bin/Release/SystemCSharp.$VERSION.nupkg" --source "nuget"
