name: Build & publish nuget
  
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.15
      with:
        versionSpec: '5.x'
    
    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0.9.7
    
    - name: Display SemVer
      run: |
        echo "SemVer: $GITVERSION_SEMVER"
        echo "NuGetVer: $NuGetVersion"

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test

    # Compile
    - name: Execute unit tests
      run: dotnet build --configuration Release

    # Build debug and release versions
    - name: Restore the application
      run: dotnet pack --configuration Release -p:Version=$NuGetVersion projectToPack.csproj

    # Actually publish the result on github packages
    - name: Publish nuget on GitHub
      run: dotnet nuget push "src/bin/Release/SystemCSharp.$NuGetVersion.nupkg" --skip-duplicate -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/jleugeri/index.json
    
    # Publish the result on NuGet.org repository
    - name: Publish nuget on NuGet.org
      run: dotnet nuget push "src/bin/Release/SystemCSharp.$NuGetVersion.nupkg" --skip-duplicate -k ${{ secrets.NUGET_ORG_API_KEY }} -s https://api.nuget.org/v3/index.json
